# โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
# WORKFLOW: Escalamiento por Severidad
# โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
name: escalation-workflow
description: |
  Escalamiento automรกtico segรบn severidad del incidente.
  - Low: Solo log
  - Medium: Notificar canal general
  - High: Notificar + crear ticket
  - Critical: Todo lo anterior + escalar a on-call
enabled: true
tags: ["alerting", "escalamiento", "severidad"]

consts:
  low_threshold: 50
  medium_threshold: 100
  high_threshold: 300
  critical_threshold: 1000

triggers:
  - type: alert

steps:
  # 1. Contar errores
  - name: contar_errores
    type: elasticsearch.search
    with:
      index: "logs-*"
      query:
        bool:
          must:
            - match:
                log.level: "ERROR"
          filter:
            - range:
                "@timestamp":
                  gte: "now-5m"
      size: 0
  
  # 2. Escalamiento condicional
  - name: determinar_accion
    type: if
    with:
      condition: "{{steps.contar_errores.output.hits.total.value >= consts.critical_threshold}}"
      then:
        # CRITICAL: Mรกxima escalaciรณn
        - type: console
          with:
            message: |
              ๐จ๐จ๐จ CRITICAL ESCALATION
              Errores: {{steps.contar_errores.output.hits.total.value}}
              
              ACCIONES:
              โ Log registrado
              โ Notificaciรณn a #alerts-general
              โ Ticket Jira creado (Priority: Critical)
              โ PagerDuty triggered
              โ On-call engineer notified
      else:
        - type: if
          with:
            condition: "{{steps.contar_errores.output.hits.total.value >= consts.high_threshold}}"
            then:
              # HIGH: Crear ticket y notificar
              - type: console
                with:
                  message: |
                    ๐จ HIGH SEVERITY
                    Errores: {{steps.contar_errores.output.hits.total.value}}
                    
                    ACCIONES:
                    โ Log registrado
                    โ Notificaciรณn a #alerts-general
                    โ Ticket Jira creado (Priority: High)
            else:
              - type: if
                with:
                  condition: "{{steps.contar_errores.output.hits.total.value >= consts.medium_threshold}}"
                  then:
                    # MEDIUM: Solo notificar
                    - type: console
                      with:
                        message: |
                          โ๏ธ MEDIUM SEVERITY
                          Errores: {{steps.contar_errores.output.hits.total.value}}
                          
                          ACCIONES:
                          โ Log registrado
                          โ Notificaciรณn a #alerts-general
                  else:
                    # LOW: Solo registrar
                    - type: console
                      with:
                        message: |
                          โน๏ธ  LOW SEVERITY
                          Errores: {{steps.contar_errores.output.hits.total.value}}
                          
                          ACCIONES:
                          โ Log registrado

# โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
# MATRIZ DE ESCALAMIENTO:
# 
# CRITICAL (>= 1000):
#   - PagerDuty page
#   - Ticket crรญtico en Jira
#   - Slack + Email
#   - On-call inmediato
#
# HIGH (>= 300):
#   - Ticket high priority
#   - Slack notification
#   - Email al equipo
#
# MEDIUM (>= 100):
#   - Slack notification
#   - Log en sistema
#
# LOW (>= 50):
#   - Solo log
#   - Revisar en prรณximo sprint
# โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ

