# ═══════════════════════════════════════════════════════════════
# WORKFLOW: Monitor de Espacio en Disco
# ═══════════════════════════════════════════════════════════════
name: disk-space-monitor
description: Monitorea espacio en disco y alerta si está bajo
enabled: true
tags: ["monitoring", "disk", "storage"]

consts:
  warning_threshold: 80
  critical_threshold: 90

triggers:
  - type: scheduled
    with:
      every: "6h"  # Cada 6 horas

steps:
  - name: check_disk_space
    type: elasticsearch.search
    with:
      index: "metrics-system-*"
      query:
        range:
          "@timestamp":
            gte: "now-10m"
      size: 1
      sort:
        - "@timestamp": desc
      _source:
        - "system.filesystem.used.pct"
        - "host.name"
  
  - name: evaluar_espacio
    type: console
    with:
      message: |
        💽 MONITOREO DE DISCO
        
        {% for hit in steps.check_disk_space.output.hits.hits limit:5 %}
        Host: {{hit._source.host.name}}
        Uso: {{hit._source.system.filesystem.used.pct | times: 100 | round: 2}}%
        
        {% if hit._source.system.filesystem.used.pct > 0.9 %}
        🚨 CRÍTICO - Espacio casi agotado
        {% elsif hit._source.system.filesystem.used.pct > 0.8 %}
        ⚠️ WARNING - Considerar limpieza
        {% else %}
        ✅ OK
        {% endif %}
        {% endfor %}

